version: '3'
services:
    postgres:
      image: postgres:16.2-alpine
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "postgres"
      ports:
        - "5432:5432"

    redis:
      container_name: redis-compose
      image: redis:7.2.4-alpine
      restart: always
      command: redis-server --save 20 1 --loglevel warning
      ports:
        - '6379:6379'



