version: '3'
services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:5432'

  redis:
    container_name: redis-compose
    image: redis:7.2.4-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '${REDIS_PORT}:6379'
